ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_postal_code VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_street VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_number VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_complement VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_neighborhood VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_city VARCHAR;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS address_state_code VARCHAR;
